accueil:
    path:     /
    defaults: { _controller: BlBundle:Vues:accueil }

articles:
    path:     /articles
    defaults: { _controller: BlBundle:Vues:articles }


archives:
    path:     /archives
    defaults: { _controller: BlBundle:Vues:archives }

article:
    path:     /article
    defaults: { _controller: BlBundle:Vues:article }

view:
    path:     /view
    defaults: { _controller: BlBundle:Vues:view }


bl:
    path:     /bl
    defaults: { _controller: BlBundle:Vues:bl }

bllist:
    path:     /bllist
    defaults: { _controller: BlBundle:Vues:bllist }

blpreview:
    path:     /blpreview/
    defaults: { _controller: BlBundle:Vues:blpreview }

blprint:
    path:     /blprint/
    defaults: { _controller: BlBundle:Vues:blprint}

bledit:
    path:     /bledit/{id}
    defaults: { _controller: BlBundle:Vues:bledit }

blconsult:
    path:     /blconsult/{id}
    defaults: { _controller: BlBundle:Vues:blconsult }

client:
    path:     /client
    defaults: { _controller: BlBundle:Vues:client }

clients:
    path:     /clients
    defaults: { _controller: BlBundle:Vues:clients }

factlist:
    path:     /factlist
    defaults: { _controller: BlBundle:Vues:factlist }

factpreview:
    path:     /factpreview
    defaults: { _controller: BlBundle:Vues:factpreview }

factconsult:
    path:     /factconsult
    defaults: { _controller: BlBundle:Vues:factconsult }

factures:
    path:     /factures
    defaults: { _controller: BlBundle:Vues:factures }

listearticles:
    path:     /listearticles
    defaults: { _controller: BlBundle:Vues:listearticles }

listeclients:
    path:     /listeclients
    defaults: { _controller: BlBundle:Vues:listeclients }

modifarticle:
    path:     /modifarticle
    defaults: { _controller: BlBundle:Vues:modifarticle }

formulaire:
    path:     /formulaire
    defaults: { _controller: BlBundle:Vues:formulaire }

nouvellefacture:
    path:     /nouvellefacture/{nom}/{prix}
    defaults: { _controller: BlBundle:Facturation:nouvellefacture }
