<?php

namespace BlBundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * BdlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BdlRepository extends \Doctrine\ORM\EntityRepository
{
}
