<?php

namespace BlBundle\Repository;

/**
 * BonslivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonslivraisonRepository extends \Doctrine\ORM\EntityRepository
{
}
