<?php

namespace BlBundle\Repository;

/**
 * BonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonsRepository extends \Doctrine\ORM\EntityRepository
{
}
