<?php

namespace BlBundle\Repository;

/**
 * ClientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientsRepository extends \Doctrine\ORM\EntityRepository
{
  public function getLikeQueryBuilder($pattern)
  {
    return $this
    ->createQueryBuilder('c')
    ->where('c.nomClient LIKE :pattern')
    ->setParameter('pattern', $pattern);
  }
}
