<?php

namespace BlBundle\Repository;

/**
 * TransporteursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransporteursRepository extends \Doctrine\ORM\EntityRepository
{
}
